### ISSUE TITLE
Cannot generate cache when passing empty string to `Only-pregenerate-world-spaces` ini value

### ISSUE THREAD

**Issue by sessionsdev** [SaneEngineer/No-Grass-In-Objects-NG#11]
There is either a bug or an error in ini documentation.  

The ini text states:
```
########################################################################################################################
#   Only pregenerate world spaces                                                                                      #
#                                                                                                                      #
# If this is not empty then skip every worldspace that isn't in this list.                                             #
#                                                                                                                      #
#    Type: (string)                                                                                                    #
########################################################################################################################
```

When the `Only-pregenerate-world-spaces = ""`, the plugin **skips** all worldspaces causing it to exit immediately with a success message.  Removing the `""` processes all worldspaces as expected. 

I'm unfamiliar with C++ and how the ini gets deserialized, but this seems like null value is handled as expected, but empty string is being treated as a valid worldspace.  Just a hunch.

**Comment by sessionsdev** [comment]
Just wanted to confirm I am using the latest `1.0.9 - New Config/Crash Fix` version

**Comment by Fizz508** [comment]
I can second this

**Comment by alandtse** [comment]
Ini files don't use `"` so an empty string is just blank.

Compare with `Skip-pregenerate-world-spaces = DLC2ApocryphaWorld;DLC01Boneyard;WindhelmPitWorldspace`

**Comment by SaneEngineer** [comment]
Looks like an oversight on my part, should be fixed no longer including an ini and generating comments with 2b9304e and 1.0.10
