### ISSUE TITLE
Not a bug, but a tip on file formatting

### ISSUE THREAD

**Issue by Fizz508** [SaneEngineer/No-Grass-In-Objects-NG#13]
When creating the .zip for the mod, you should properly format it so it's easier to install.

So instead of having to manually extract the files into the \Plugins folder, we can simply click "install from file" in vortex(might be the same for MO2 idk), and viola it's installed.

Example:

Create a folder named "SKSE", then create another folder inside of that named "Plugins", and place the mod files inside the plugins folder, then right click the created SKSE folder, click "add to archive", ".ZIP", and "Ok". And post that as the zip instead. The name of the created .zip can be whatever you want, 

And I'm suggesting this to reduce the amount of problems you'll have to be solving. You'll have less people reporting issues on it "not working" when in reality they just placed something in the wrong folder.

Also I noticed an issue with deleting the original GrassControl.ini, the one that shows up after lacks all the context originally provided with the settings.

Hope this helped.

**Comment by SaneEngineer** [comment]
Thanks, the generated ini with 1.0.10 should now generate the same context and I will keep the folder structure in mind. I completely forgot, as I did this with the initial release.
