### ISSUE TITLE
No Ini File Included With V1.0.10 Zip File?

### ISSUE THREAD

**Issue by Zanderat** [SaneEngineer/No-Grass-In-Objects-NG#14]
Should there be one?  Thanks!

**Comment by SaneEngineer** [comment]
The mod will now generate an ini file the first time it is loaded.

**Comment by Zanderat** [comment]
Got it.  This is good for testing.  But for general release I suggest adding back the descriptive comments.

**Comment by SaneEngineer** [comment]
They should be created with release 1.0.10 with you generate a new ini.
