### ISSUE TITLE
Accept malformed INI strings

### ISSUE THREAD

**Issue by alandtse** [SaneEngineer/No-Grass-In-Objects-NG#16]
**Describe the bug**
INI files do not require quotes. However, users will invariably quote things. We should look at all "string" types and autostrip quotes.

**Screenshots**

**Caching**
If you are having issues with Caching, please upload PrecacheGrass.txt

**Config**
Please upload your GrassControl.ini

**Log**
Please upload your NGIO.log here or link from pastebin

**Additional context**

**Comment by SaneEngineer** [comment]
Implemented in 6a3bfa8
