### ISSUE TITLE
Generate Empty files

### ISSUE THREAD

**Issue by Tiagox42** [SaneEngineer/No-Grass-In-Objects-NG#19]
**Describe the bug**

I performed all the configurations as described in the "MO2 Installation Instructions." Upon enabling the "Precache grass" option, the game starts normally but remains on the menu screen without further progress. I'm unsure if it should stay on this screen, but I'd like to note this behavior.

I left the game in this state for over an hour, finding it peculiar that it didn't proceed. Upon closing the game, I received the success message. However, upon checking the "overwrite" folder, I found only one file named "PrecacheGrass.txt," empty, with no content. Additionally, the "GrassControl.ini" file was not generated.

I tested both the latest version and 1.0.9, obtaining the same results in both cases. There were no crashes to provide additional reports.

Overwrite folder print:

![image](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/19379148/93995121-ffbd-4905-9826-6517d357928b)

**Comment by SaneEngineer** [comment]
A loading screen should open with a popup saying Grass Caching is occurring when the main menu shows up. Do you have the MO2 plugin rootbuilder as that may be conflicting? Could you also post your NGIO-NG.log.

**Comment by SaneEngineer** [comment]
Also make sure you do not have a GrassControl.ini in `SKSE/Plugins/` already, as a new one will not be generated and thus will not show up under overrides.

**Comment by Tiagox42** [comment]
I was able to find GrassControl.ini, now setting **Use-grass-cache = true, Only-load-from-cache = true**, the cache was loaded. Thanks for the support.

I didn't need to activate the root plugin, is compatible.
