### ISSUE TITLE
Grass Disappears Then Reappears When Approaching Sometimes

### ISSUE THREAD

**Issue by 0pLuS0** [SaneEngineer/No-Grass-In-Objects-NG#23]
**Describe the bug**
When I get close to grass, sometimes the grass will disappear, then reappear. I've had this happening in the past before using this mod with the original NGIO, but maybe there is a NGIO issue here in regards to the grass cache and the settings I use.

For the life of me I have no idea what causes this...

**Screenshots**
I made a video and posted it on Vimeo. Right at 10-12 seconds out in the distance to my left, then straight ahead, and to the right, a huge section of the grass disappears, and it becomes more brown in color where the grass use to be, then it reappears.

https://vimeo.com/938490482

**Caching**
If you are having issues with Caching, please upload PrecacheGrass.txt

**Config**
Please upload your GrassControl.ini
[GrassControl.ini.txt](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/files/15088436/GrassControl.ini.txt)

**Log**
Please upload your NGIO.log here or link from pastebin
[NGIO-NG.log](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/files/15088438/NGIO-NG.log)

**Additional context**
I am running SSE 1.6.640.0 with Tamrielic Grass and Tamrielic Grass for ENB Complex Grass, and I use xLODGen, TexGen and DynDOLOD 3.

Tamrielic Grass has a Tamrielic Grass.ini file, these are it's settings.

[Grass]
fGrassMaxStartFadeDistance=17000.0000
fGrassMinStartFadeDistance=0.0000
iMaxGrassTypesPerTexure=13
iMinGrassSize=52

These are the settings I use in Skyrim.ini

[Grass]
bAllowCreateGrass=0
bAllowLoadGrass=1
bDrawShaderGrass=1
bEnableGrassFade=0
fGrassFadeRange=14128
fGrassMaxStartFadeDistance=17000.0000
fGrassMinStartFadeDistance=0.0000
fGrassWindMagnitudeMax=125
fGrassWindMagnitudeMin=5
iGrassCellRadius=2
iMaxGrassTypesPerTexure=13
iMinGrassSize=52

These are the grass settings I use in SkyrimPrefs.ini.

[Grass]
fGrassMaxStartFadeDistance=17000.0000
fGrassMinStartFadeDistance=0.0000
fGrassStartFadeDistance=17000.0000

These are grass settings I use in SkyrimCustom.ini

[Display]
bShadowsOnGrass=1

THANKS

**Comment by SaneEngineer** [comment]
This is an issue with transitioning from LOD grass to actual grass. This an issue inherited from the original mod. This is something that will eventually be fixed but will take time. The only solution right now is to set DynDOLOD-Grass-Mode = 2 which uses NGIO's extended grass distance feature, which currently has issue for certain users.

**Comment by 0pLuS0** [comment]
THANKS a lot for everything!

This mod is really great!

Keep up the amazing work, it is truly appreciated!

You make Skyrim a better place! 👍

**Comment by ikonomov** [comment]
I believe I had a similar issue (prior to NGIO NG), basically having to do with the grass being unloaded too early in the loaded cell try these settings:
Skyrim.ini
[Grass]
fGrassMaxStartFadeDistance=20272.0000
_
SkyrimPrefs.ini
[Grass]
fGrassStartFadeDistance=20272
fGrassMaxStartFadeDistance=20272.0000

**Comment by 0pLuS0** [comment]
@ikonomov 

I mentioned I've had this happening in the past too with the original NGIO, it's been an ongoing issue for me, for the past 2 years.

One of the settings I posted for the SkyrimPrefs.ini were incorrect, it's this;

[Grass]
fGrassMaxStartFadeDistance=17000.0000
fGrassMinStartFadeDistance=0.0000
fGrassStartFadeDistance=17000.0000

In the Skyrim.ini

fGrassMaxStartFadeDistance=17000.0000
fGrassMinStartFadeDistance=0.0000

I use 17000.0000 because as I mentioned Tamrielic Grass has a Tamrielic Grass.ini file, these are it's settings.

[Grass]
fGrassMaxStartFadeDistance=17000.0000
fGrassMinStartFadeDistance=0.0000
iMaxGrassTypesPerTexure=13
iMinGrassSize=52

I assumed if Tamrielic Grass is using 17000.0000, going above it, might not work as well for the mod...

THANKS

**Comment by ikonomov** [comment]
You can read why 20272.0000 is the number that you want to use with grass billboards here: https://stepmodifications.org/forum/topic/19454-full-grass-fade-range-in-active-cells/  fGrassMaxStartFadeDistance (and fGrassStartFadeDistance) is the distance at which grass starts to fade into the distance, a feature that you only want to use when you are not using grass billboards.  Extending the distance by using 20272.0000 essentially disables the fading feature so that grass does not fade into the distance.  There is no guarantee that using 20272.0000 will fix your issue, because it's possible that you are experiencing a completely different problem.  However, it's worth a try and also it's easy to test.  I had a similar issue and it fixed my problem.  By the way 17000.0000 is just a random number that the creator of Tamrielic Grass decided to use likely because it creates a grass fade that looked good.  It has no effect on the generation of the cache or billboards or even the look of the grass itself.

**Comment by 0pLuS0** [comment]
I noticed you made fGrassStartFadeDistance=20272 without the zeros on the end like the others? .0000

Does it really matter?

THANKS I'll certainly try this, much appreciated!

**Comment by 0pLuS0** [comment]
@ikonomov I had the grass disappear as I approached it using 20272.0000, and the closer I go, it never reappeared.

But then a few minutes later the game froze and did a CTD too.

Maybe still issues that need working out with NGIO. hmm

**Comment by 0pLuS0** [comment]
With NGIO-NG-1.0.12-1.6.640 I'm still running into grass rendering issues.

1. Sometimes the grass will disappear when I approach it then reappear.
2. I see areas around near the Sleeping Tree in the Tundra near Whiterun where grass is not being rendered, but empty.
3. I'm also seeing areas near the Sleeping Tree in the Tundra near Whiterun where the grass in the distance isn't rendered properly, but in patches and blotches, not full.

I'm also seeing some floating grass, but I am using Complex Grass which I haven't used miuch before, so not sure if it's the issue, I'll test this further and let you know.

Here's a screen shot of the grass clumps in the distance not appearing full at this distance, which it did before with the original NGIO. All the bright areas of individual looking blades, it didn't render like this before.

![Grass Clumps](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/36190223/0673a22a-f87e-4895-9795-8e079f532e94)

Here's an area that no grass rendered.

![GrassRender](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/36190223/67699cca-bd08-497d-97c9-c379a08b4753)

In this screen shot, it's the area in the previous screen shot above, the location I moved to where the two red X are at. As I approached this area, the grass in the distance disappeared that I placed 3 red X at.

![Grass Disappears](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/36190223/657a3c37-f522-4b9c-9532-cb300468b7b2)

**Comment by 0pLuS0** [comment]
Using DynDOLOD-Grass-Mode = 1 I didn't notice any barren areas without grass, but I didn't ride around as long, but it does look better so far.

Using 20272.0000 I'm not seeing any differences, with pop in, and the grass still disappears and reappears sometimes as I'm approaching it. hmm

THANKS

**Comment by ikonomov** [comment]
If you are using Mode 1 together with GrassStartFadeDistance 20272 the fGrassFadeRange doesn't matter because the entire loaded cell will be covered by grass regardless of your position in it.  Whatever issue you are running into, it must be something else.

**Comment by 0pLuS0** [comment]
@ikonomov the last post I made with the screen shots I posted was using DynDOLOD-Grass-Mode = 2 

All I know is with this Mode 2 it becomes more noticeable, but then large areas of grass are also not being rendered with Mode = 2.

Does DynDOLOD-Grass-Mode = 2 work?

Also with grass disappearing and then popping into view, this doesn't always happen. Sometimes I load a game save and I see it 1 time, then I load that same game save over many times, go back to that same area and never seen it again. So I don't understand why the same particular area might do this sometimes then other times not.

I'm not sure if I have a mod conflicting, or what the problem is.

THANKS

**Comment by SaneEngineer** [comment]
There is still some issues with DynDOLOD-Grass-Mode = 2. Here is a test build which should fix some of the issues.
[NGIO-NG.zip](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/files/15144154/NGIO-NG.zip)

**Comment by 0pLuS0** [comment]
Hi @SaneEngineer 

I forgot to mention, I'm starting to think the reason maybe I see grass disappear then pop in, possibly it has to do with my Game Saves, because I assume, if I am making changes to my setup and then load a previous game save with different grass settings, it's the reasons for this.

Is DynDOLOD-Grass-Mode = 2 a better Mode to use?

THANKS

**Comment by 0pLuS0** [comment]
I should of uploaded the INI before, these are the BethINI High settings, with just a few changes, mainly for the grass.

I have uGridsToLoad = 5.

[Skyrim.ini.txt](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/files/15144436/Skyrim.ini.txt)

[SkyrimPrefs.ini.txt](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/files/15144440/SkyrimPrefs.ini.txt)

[SkyrimCustom.ini.txt](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/files/15144441/SkyrimCustom.ini.txt)

THANKS

**Comment by SaneEngineer** [comment]
I was suggesting that another mod like how Tamrielic Grass has settings in Tamrielic Grass.ini. may be overwriting uGridsToLoad

**Comment by 0pLuS0** [comment]
This is the original TamrielicGrass.ini

[Grass]
fGrassMaxStartFadeDistance=17000.0000
fGrassMinStartFadeDistance=0.0000
iMaxGrassTypesPerTexure=13
iMinGrassSize=52

I changed it to;

[Grass]
fGrassMaxStartFadeDistance=20272.0000
fGrassMinStartFadeDistance=0.0000
iMaxGrassTypesPerTexure=15
iMinGrassSize=50

The Complex Grass has the same ini and settings.

THANKS

**Comment by SaneEngineer** [comment]
I was just using tamrielic grass as an example

**Comment by 0pLuS0** [comment]
DynDOLOD-Grass-Mode = 2 is working nice now.

I ran around the Tundra from Whiterun past the Sleeping Tree and further, I didn't see any blank areas with no grass, and I also didn't see any grass disappear and reappear.

Keep up the great work, it's really appreciated, you make Skyim a better place!

BIG THANKS

**Comment by 0pLuS0** [comment]
Hmm now it's not working again DynDOLOD-Grass-Mode = 2.

The only thing I did was change ```Ensure-max-grass-types-setting``` from 15 to 13 and '''Overwrite-min-grass-size''' from 50 to 52. I also updated those changes in the Skyrim.ini and for Tamrielic Grass and the Complex Grass I updated those changes in the Tamrielic Grass.ini.

I also used ```Edmond's Tamrielic Grass ESL - And Green Snow Grass Removal and River Fix```
https://www.nexusmods.com/skyrimspecialedition/mods/84501

Hmm, not sure what threw it off again. I'll try it over without  ```Edmond's Tamrielic Grass ESL - And Green Snow Grass Removal and River Fix```

![No Grass](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/36190223/df5fb005-d06c-4fd2-93c3-3df077d05688)

**Comment by SaneEngineer** [comment]
Thanks for the kind words. Did you ever test TrueHUD with caching?

**Comment by 0pLuS0** [comment]
> Thanks for the kind words. Did you ever test TrueHUD with caching?

I just grabbed 1.0.13 and it started to restart twice, the first 2-3 minutes in the beginning, so I stopped it.

All l know is, with it enabled it restarts 5x-6x more, and takes longer.

If I uncheck it, it only begins to restart when it reaches the end of the cache process like World 43 out of 43, and it restarts only 5 times.

**Comment by SaneEngineer** [comment]
Thanks for testing that. I'm going to close out this issue and cover any similar issues on the nexus page.

**Comment by 0pLuS0** [comment]
I don't follow, cover any similar issues on Nexus? 

When you have time, will you still be trying to figure this out?

THANKS

**Comment by SaneEngineer** [comment]
If any else has this issue, I'll communicate on the nexus issue so that more people can see it. I'll keep looking into trueHUD.
