### ISSUE TITLE
DynDOLOD-Grass-Mode = 2 - Causes CTD & No Grass Rendered

### ISSUE THREAD

**Issue by 0pLuS0** [SaneEngineer/No-Grass-In-Objects-NG#24]
**Describe the bug**

I'm using SSE 1.6.640.0 with Tamrielic Grass and Complex Grass for Tamrielic Grass.

Using ```DynDOLOD-Grass-Mode = 2``` in the ```GrassControl.ini``` causes grass to not be rendered up close, and then partially rendered in the distance. If I load a game save that is indoors like at Warmaiden's in Whiterun, as soon as I step outside I get a CTD. If I load a game save outside, I then see grass rendering issue(s).

When I used ```DynDOLOD-Grass-Mode = 1``` the grass rendered nicely and there were no CTD.

**Screenshots**
Here's a game save, just outside Whiterun, the Red X are where the grass is not rendering close up, and the two Green Question marks are where the grass renders, but not 100%. If you look closely at the grass where the green question marks are, you can see what appears like a lot of individual bright pieces of grass sticking up alone, along with some other grass that is slightly darker. Tamrielic Grass grass does not look like this in the distance with the bright chunks, it looks nice and full.

![No Rendering](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/36190223/9ce595b2-f6e3-4008-8360-7377a0424d56)

**Caching**
If you are having issues with Caching, please upload PrecacheGrass.txt

**Config**
Please upload your GrassControl.ini
[GrassControl.ini.txt](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/files/15092091/GrassControl.ini.txt)

**Log**
Please upload your NGIO.log here or link from pastebin
[NGIO-NG.log](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/files/15092096/NGIO-NG.log)

Here is a log from Trainwreck when I got the CTD.
[Trainwreck LOG.log](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/files/15092098/Trainwreck.LOG.log)

**Additional context**

THANKS

**Comment by SaneEngineer** [comment]
1.0.12 might fix this issue, but I will also attach a test build 1.0.13 that think is much more likely to fix this issue. 
[NGIO-NG-1.0.13-AE.zip](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/files/15098593/NGIO-NG-1.0.13-AE.zip)

**Comment by 0pLuS0** [comment]
Hi @SaneEngineer 

I just tried 1.0.13, it's the same, CTD when I try and go outside from Warmaiden's and when I load a game save outside in the Tundra outside near Whiterun, like the screen shot I posted, the same grass issue(s).

THANKS

**Comment by SaneEngineer** [comment]
Both DynDOLOD modes in NGIO set the value to 999999.0000, set DynDOLOD mode to 0. All it does is toggle settings.

**Comment by 0pLuS0** [comment]
You want me to now test DynDOLOD-Grass-Mode = 0?

THANKS

**Comment by SaneEngineer** [comment]
Yes and make sure to set fGrassStartFadeDistance to 17000.0.

DynDOLOD-Grass-Mode = 1 and 
DynDOLOD-Grass-Mode = 2 both set fGrassStartFadeDistance to 999999

**Comment by 0pLuS0** [comment]
Ok on 1 and 2...

For the moment I was going to try out  20272.0000 that ikonomov metioned, unless for your testing you need me to keep at 17000 for now?

THANKS

**Comment by SaneEngineer** [comment]
Either works I just used that value as an example,

**Comment by 0pLuS0** [comment]
I just finished running the grass cache. I received a popup saying the game is frozen and click ok to continue, never seen that before. Also I have two .fail files. Are these fail files bad, like eventually as the development of NGIO progresses, these cells shouldn't be skipped?

THANKS

![Fail](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/36190223/ff71430a-7017-4b03-b687-7278f0ac9ff8)

**Comment by SaneEngineer** [comment]
Fail files mean that those two cells were skipped because they crashed more than MaxFailures and grass was not generated for them.

**Comment by SaneEngineer** [comment]
Cells should not need to be skipped.

**Comment by SaneEngineer** [comment]
DynDOLOD-Grass-Mode = 2 should be fixed with [1.0.12-1.6.640](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/releases/download/1.0.12/NGIO-NG-1.0.12-1.6.640.zip)

**Comment by ikonomov** [comment]
> @ikonomov mentions using 20272.0000 for the grass settings in this reply, and I'd like to test this if DynDOLOD-Grass-Mode = 2 is changing it.
> 

20272 value for fGrassStartFadeDistance is only relevant when using mode 1.  With mode 2 you can use whatever distance allows you to keep acceptable framerate.

**Comment by 0pLuS0** [comment]
@SaneEngineer it's the same issues using ```DynDOLOD-Grass-Mode = 2``` CTD and grass rendering...

**Comment by SaneEngineer** [comment]
Disregard 1.0.13, did you try using [1.0.12-1.6.640](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/releases/download/1.0.12/NGIO-NG-1.0.12-1.6.640.zip) or the regular [NGIO-NG-1.0.12-AE.zip](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/releases/download/1.0.12/NGIO-NG-1.0.12-AE.zip)?

**Comment by 0pLuS0** [comment]
Ok on 1.0.13, I will try 1.0.12-1.6.640 now.

THANKS

**Comment by 0pLuS0** [comment]
DynDOLOD-Grass-Mode = 2 with 1.0.12-1.6.640 is working ok! 

Thanks for all your support, keep up the great work! I will certainly report if anything else comes up to help you!

**Comment by 0pLuS0** [comment]
I spoke to soon... :face_exhaling: 

I was outside of Whiterun running around on the horse in the Tundra and the game froze then did CTD.

**Comment by 0pLuS0** [comment]
I didn't have a crash log, I'll keep trainwreck installed if it does it again.

THANKS

**Comment by SaneEngineer** [comment]
I'm going to close out this issue for anyone with issues with DynDOLOD-Grass-Mode = 2/Extend-Grass-Distance = true will be covered in issue #30.

For [0pLuS0](https://github.com/0pLuS0), if you have anymore issues use issue #23.
