### ISSUE TITLE
Grass doesn't render when Extend-grass-distance=true in some areas.

### ISSUE THREAD

**Issue by cyberrumor** [SaneEngineer/No-Grass-In-Objects-NG#30]
**Describe the bug**
When using Extend-grass-distance=false, grass correctly renders in all areas. When using Extend-grass-distance=true, grass renders in some areas (like outside of Whiterun) but not in others (like outside of Riften).

**Screenshots**
Screenshots are taken with the ini uploaded below, and the only change is whether Extend-grass-distance is true or false.

`Extend-grass-distance = true`, grass does not render in Riften outskirts:
![screenshot_028](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/46626673/6a041903-f736-45ba-96f0-9542c21fe3a1)

`Extend-grass-distance = false`, grass correctly renders in Riften outskirts:
![screenshot_027](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/46626673/be4b4be0-bd10-4b54-b931-c50c5cf5940b)

**Caching**
No issues with caching, I have the expected grass cache files in `Data/grass/`. PrecacheGrass.txt was created with the 'touch' command, if that matters. This issue has been reproducible for me whether the cache is generated with vanilla grass or Folkvangr, as well as either generating a cache for only Tamriel or all worldspaces. The grass cache was generated using Extend-grass-distance=false, iirc.

**Config**
Please upload your [GrassControl.ini.txt](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/files/15136125/GrassControl.ini.txt). Note that my actual file extension is .ini not .ini.txt, just added .txt to get around github's file type filters.

**Log**
Please upload your NGIO.log here or[ link from pastebin](https://paste.debian.net/1315317/)
[skse64.log pastebin](https://paste.debian.net/1315320/)

**Additional context**
- Game build number (from steam) is 13189953.
- Game version is 1.6.1170.0.8
- SKSE64 version is 2.2.6
- Address Library is version 11, "All in one Address Library (Anniversary Edition)". None of the optional DLL files were used.
- NGIO-NG version is 1.0.12AE
- Complete list of mods used: skse64, address lib, and No-Grass-In-Objects-NG.

I concede I am running this on Linux through Proton Experimental. A fast way to reproduce is: after generating a proper grass cache type `coc riftenstables` from the main menu, then exit the stables and observe presence/absence of grass. You can also use `coc whiterunstables` then exit the stables for Whiterun. Strangely, the grass does not appear to be negatively impacted by changes to this setting when outside of Whiterun (it renders outside of Whiterun regardless of true/false). It is possible that the outskirts of Riften are not the only impacted area, though.

Great work btw, thanks so much for bringing this mod to SKSE. I never did have luck with the original mod with all the downgrade patching and weird dependencies.

**Comment by Zanderat** [comment]
I can confirm about lack of grass in Riften.  Seems like it should be there.  

Only-pregenerate-world-spaces = "3DNPCGabaniasWorld;AlftandWorld;Blackreach;BlindCliffCaveWorld;BloatedMansGrottoWorld;BluePalaceWingWorld;BrinewaterGrottoWorld;BSKHyorkerIsle;DarkwaterWorld;DeepwoodRedoubtWorld;DLC01Boneyard;DLC01FalmerValley;DLC01SoulCairn;DLC1AncestorsGladeWorld;DLC1DarkfallPassageWorld;DLC1ForebearsHoldout;DLC1HunterHQWorld;DLC1VampireCastleCourtyard;DLC2SolstheimWorld;EastEmpireWarehouse;ECSSShiveringIsles;ECSSzDummyMarkerWorld;EldergleamSanctuaryWorld;elf0coracaodaguardiaworld;elf0partycampdestinyoflove;elf0partycampworld;elf0partycampworldtent;EUMonsterCaveWorld;FallowstoneCaveWorldEnd;FallowstoneCaveWorldStart;FrostmereCryptWorld;JaphetsFollyWorld;KarthspireRedoubtWorld;KatariahWorld;LabyrinthianWorld03;LabyrinthianWorld04;MarkarthWorld;MossMotherCavernWorld;RedEagleRedoubtWorld;RiftenWorld;ShadowgreenCavernWorld;SkuldafnWorld;SolitudeWorld;Sovngarde;Tamriel;WhiterunDragonsreachWorld;WhiterunWorld;WindhelmPitWorldspace;WindhelmWorld;zAoMWitchWorld;zBMLamaeWorld;zCHOldForestWorld;zCHTrueEndWorld;zCOBruiantWorld"

**Comment by SaneEngineer** [comment]
Should be fixed with 1.0.13

**Comment by cyberrumor** [comment]
Just ran a quick test, appears to be fixed. Thanks a bunch!

**Comment by Zanderat** [comment]
Yes.  Grass is back using the Riften Stables test.  Thanks!
