### ISSUE TITLE
Suggestion: Seasons support

### ISSUE THREAD

**Issue by Foozey** [SaneEngineer/No-Grass-In-Objects-NG#32]
Love the port, seems to be working fine for me!

I know it's not in the original, but I would love to see seasons support in this version, meaning if you have "load from cache" enabled, it will correctly select the appropriate seasonal cache to pull from. Seasonal grass cache contains an extension for each season for example .AUT.cgid, or .WIN.cgid.

**Comment by SaneEngineer** [comment]
Sorry for the late respond, but I tried for a while to get this working, but unfortunately I have not been able to get working. I'm not sure why, since Grass Cache Helper NG provides support for seasons, I recommend just using that as I does not conflict.
