### ISSUE TITLE
Empty grass directory keeps appearing in MO2 overwrite directory

### ISSUE THREAD

**Issue by 0pLuS0** [SaneEngineer/No-Grass-In-Objects-NG#36]
**Describe the bug**
Describe what you we're doing when the bug occurred. 

I'm running SSE 1.6.640.0, NGIO - Anniversary Edition (1.6.629 to 1.6.659)-42161-1-0-16f2 and MO2 2.5.0

I've noticed several times an empty ```grass``` directory appears in the MO2 overwrite directory, and I have no idea what causes this.

**Config**
Please upload your GrassControl.ini
[GrassControl.ini.txt](https://github.com/user-attachments/files/15750832/GrassControl.ini.txt)

**Log**
Please upload your NGIO.log here or link from pastebin
[NGIO-NG.log.txt](https://github.com/user-attachments/files/15750833/NGIO-NG.log.txt)

THANKS

**Comment by 0pLuS0** [comment]
I just figured out what is causing this.

If I disable the grass cache in MO2, when I start the game, it will then create an empty grass directory in overwrite.

For various reasons, when I've run into mod issues, I've disabled the grass cache several times, but wasn't paying attention, now I see this is the issue.

THANKS

**Comment by SaneEngineer** [comment]
I'm glad you found a solution.

**Comment by 0pLuS0** [comment]
> I'm glad you found a solution.

I didn't find a solution, I found the reason the empty directory was being created.

I reported this, so it can be fixed and not create an empty directory when someone disables it for whatever reasons. I didn't think it should be doing this.

THANKS

**Comment by SaneEngineer** [comment]
Sorry about that, I found a fix. I'll have a release out soon.
