### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by robertgk2017** [SaneEngineer/No-Grass-In-Objects-NG#38]
**Describe the bug**
Game insta ctds upon entering various cell, with NGIO disabeld game loads cell just fine.

**Screenshots**
No screenshots available

**Caching**
If you are having issues with Caching, please upload PrecacheGrass.txt

**Config**
Please upload your GrassControl.ini
[GrassControl.txt](https://github.com/user-attachments/files/15922778/GrassControl.txt)

**Log**
Please upload your NGIO.log here or link from pastebin
[NGIO-NG.log](https://github.com/user-attachments/files/15922779/NGIO-NG.log)

**Additional context**
Crash log.
[crash-2024-06-21-04-35-44.log](https://github.com/user-attachments/files/15922781/crash-2024-06-21-04-35-44.log)

Log makes it out to be an issue with a certain LAND/GRAS mesh though upon inspection they appear to be valid/correct. 

Edit: oh 1.6.1170, latest NGIO Version 1.0.16f

**Comment by SaneEngineer** [comment]
I created a test build that might fix this issue. Give it a try and let me know. [NGIO-NG_1.0.17.1.7z](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/releases/download/1.0.17/NGIO-NG_1.0.17.1.7z)
