### ISSUE TITLE
Cannot run NGIO at all - Failed to create more grass shapes.

### ISSUE THREAD

**Issue by primem0ver** [SaneEngineer/No-Grass-In-Objects-NG#39]
**Describe the bug**
Starting NGIO for the first time.  Repeated attempts  I have ExtendGrassCount = True and it is crashing and giving me the text from line 239 in Hooks.dll's code ("Failed to create more grass shapes").  I set this because my grass count is 20 instead of 15 or lower.  I can skip this if it isn't necessary but curious why this is causing an issue.

**Screenshots**

**Caching**
If you are having issues with Caching, please upload PrecacheGrass.txt

**Config**
;This will generate cache files in /Data/Grass/ and use those when we have them. Any time you change anything with your mod setup you must delete the contents of that directory so new cache can be generated or you will have bugs like floating grass or still grass in objects(that were changed by mods).
Use-grass-cache = false

;Set true if you want to enable extended grass distance mode. This will allow grass to appear outside of loaded cells.Relevant ini settings : SkyrimPrefs.ini[Grass] fGrassStartFadeDistance
Extend-grass-distance = false

;Allow more grass to be made in total. This is needed if you use very dense grass or have large draw distance. Otherwise it will reach a limit and just stop making grass leaving weird empty squares.
Extend-grass-count = true

;Makes sure that the max grass types per texture setting is set to at least this much. Can be useful to make sure your INI isn't being overwritten by anything. Most grass replacer mods require this. Set 0 to disable any verification.
Ensure-max-grass-types-setting = 7

;Overwrite fGrassStartFadeDistance from any INI. If this is zero or higher then the grass distance will always be taken from this configuration instead of any INI.This can be useful if you have a million things overwriting your INI files and don't know what to edit, so you can just set it here. For example 7000 is vanilla highest in-game grass slider. If you want to set higher you need to enable ExtendGrassDistance setting as well or it will not look right in - game. What the setting actually means is that grass will start to fade out at this distance. Actual total grass distance is this value + fade range value.
Overwrite-grass-distance = 6000.000000

;Overwrite fGrassFadeRange from any INI. If this is zero or higher then the grass fade range will always be taken from this configuration instead of any INI. This determines the distance it takes for grass to completely fade out starting from OverwriteGrassDistance(or fGrassStartFadeDistance if you didn't use the overwrite). If you want the grass fade out to not be so sudden then increase this value.Probably recommended to keep this at least half of the other setting.
Overwrite-grass-fade-range = 3000.000000

;Overwrite iMinGrassSize from any INI. If this is zero or higher then the grass density setting (iMinGrassSize) will be taken from here instead of INI files. Lower values means more dense grass. 50 or 60 is normal mode with somewhat sparse grass(good performance).Lowering the value increases density !20 is very high density. You should probably not set lower than 20 if you decide to change it. The grass form density setting itself still mostly controls the actual density of grass, think of iMinGrassSize more of as a cap for that setting.
Overwrite-min-grass-size = -1

;Apply this scale to every piece of grass everywhere. For example 0.5 makes all grass pieces half the size it should be.
Global-grass-scale = 1.000000

;This will change how grass works. It means grass can only ever be loaded from files and not generated during play.
Only-load-from-cache = false

;When pre-generating grass then skip worldspaces with this editor IDs. This can greatly speed up generating if we know the worldspace will not need grass at all.
Skip-pregenerate-world-spaces = DLC2ApocryphaWorld;DLC01Boneyard;WindhelmPitWorldspace

;If this is not empty then skip every worldspace that isn't in this list.
Only-pregenerate-world-spaces = 

;Enable grass compatibility mode with DynDOLOD Grass LODs. Valid values: 0 = Disabled; 1 = Display grass only in active cells(without fade) and let DynDOLOD handle inactive cell Grass; 2 = Display grass only in active cells and large ref loaded cells(without fade) and let DynDOLOD handle grass outside of large ref cells 
DynDOLOD-Grass-Mode = 0

;Maximum number of attempts to generate a grass cache before skipping a cell.
Max-Failures = 2

;Enable or disable the freeze check that is run while generating a grass cache. Recommended to leave enabled unless the message repeately appears.
Freeze-check-enabled = true

**Log**
Please upload your NGIO.log here or link from pastebin
If you are talking about logs from [USER FOLDER]\Documents\My Games\Skyrim Special Edition\Logs, then there is no NGIO.log...

**Additional context**

**Comment by SaneEngineer** [comment]
This typically occurs when you have the old Net Script version of the mod still installed, as two obviously conflict. If not, I'd verify your game because otherwise it means the mod is having issues patching the game because it is not what it expected to find. Just in case, what game version are mod version are you using. 

Yes, also the log will be in [USER FOLDER]\Documents\My Games\Skyrim Special Edition\SKSE and named NGIO-NG.log
