### ISSUE TITLE
The grass cache process wont start

### ISSUE THREAD

**Issue by goober442** [SaneEngineer/No-Grass-In-Objects-NG#6]
I'm honestly at a loss. All of the right settings are enabled in the mod's TOML and I have the PrecacheGrass.txt file in Skyrim's root folder. Unfortunately the game keeps starting as normal. Any help at all would be highly appreciated.

**Comment by SaneEngineer** [comment]
Could you please post your toml and NGIO-NG.log. Thank you.

**Comment by goober442** [comment]
I will when I'm next able to access my computer. I did look for the NGIO log at some point though and was not able to find it where it was supposed to be.

**Comment by AllstaRawR** [comment]
@goober442 Maybe I'm understanding this wrong, but are you saying that you expect to launch the game normally, through SKSE, and it will just start caching? I did not know that was an option. I was using the MO2 plugin from the original NGIO [here](https://www.nexusmods.com/skyrimspecialedition/mods/42161/?tab=files) to generate grass cache, modified slightly as seen here.
![Screenshot 2024-04-20 075350](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/164591926/d8570db0-bb81-4c1c-a145-4ef30c4cac35)

**Comment by jsghines** [comment]
> @goober442 Maybe I'm understanding this wrong, but are you saying that you expect to launch the game normally, through SKSE, and it will just start caching? I did not know that was an option. I was using the MO2 plugin from the original NGIO [here](https://www.nexusmods.com/skyrimspecialedition/mods/42161/?tab=files) to generate grass cache, modified slightly as seen here. Do I not need to use a MO2 plugin and the DLL actually takes care of this on its own? ![Screenshot 2024-04-20 075350](https://private-user-images.githubusercontent.com/164591926/324178598-d8570db0-bb81-4c1c-a145-4ef30c4cac35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MzA2MzAsIm5iZiI6MTcxMzYzMDMzMCwicGF0aCI6Ii8xNjQ1OTE5MjYvMzI0MTc4NTk4LWQ4NTcwZGIwLWJiODEtNGMxYy1hMTQ1LTRlZjMwYzRjYWMzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQxNjI1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzI1MGVjMTgzZWUwMzdlODA0NjAwNjZiYzUyMzBkMGM2ZmQxNjA0N2M5OGJkZjMwNGY4OGRmYjc0NGExYjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qz4oaXZ0RDIe-h42kxwt2z0GuZrABcae3CYv8hb5W7A)

If the game sees a PrecacheGrass.txt file in the root folder, it will automatically run the grass caching process on game launch. I also tried modifying the script but it has issues with the NG version, it will only randomly render some of the worldspaces and then erroneously claim it's finished.

**Comment by goober442** [comment]
> Could you please post your toml and NGIO-NG.log. Thank you.

[grass control.txt](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/files/15049273/grass.control.txt)

Here it is, I had to transfer the contents of the TOML into a text document since Github wouldn't let me send the TOML itself. Theres still no log though.

**Comment by SaneEngineer** [comment]
Sorry for the confusion, the change in config comes with an issue, Skip-pregenerate-world-spaces and Only-pregenerate-world-spaces need to be on the same line, otherwise only the first worldspace will be read.

**Comment by SaneEngineer** [comment]
@goober442 Can you check C:\Users\YOUR_USERNAME_HERE\Documents\My Games\Skyrim Special Edition\SKSE\skse64.log
and see if NGIO-NG.dll shows up in the log.

**Comment by goober442** [comment]
> Sorry for the confusion, the change in config comes with an issue, Skip-pregenerate-world-spaces and Only-pregenerate-world-spaces need to be on the same line, otherwise only the first worldspace will be read.

Alright I'll try that, thank you.

**Comment by goober442** [comment]
> Sorry for the confusion, the change in config comes with an issue, Skip-pregenerate-world-spaces and Only-pregenerate-world-spaces need to be on the same line, otherwise only the first worldspace will be read.
How should they look on the same line exactly? And when I copy one and move it to the other's line do I delete the original?

**Comment by SaneEngineer** [comment]
For reference look at Skip-pregenerate-world-spaces. The line should look like this with the semi-colons separating the world spaces. Also makes sure to remove the quotation marks around the worldspace with version 1.0.9 or 1.0.10.
Only-pregenerate-world-spaces = DLC2ApocryphaWorld;DLC01Boneyard;WindhelmPitWorldspace

**Comment by goober442** [comment]
> @goober442 Can you check C:\Users\YOUR_USERNAME_HERE\Documents\My Games\Skyrim Special Edition\SKSE\skse64.log and see if NGIO-NG.dll shows up in the log.

It doesn't.

**Comment by goober442** [comment]
I may have to try this with MO2 and see if it is just an issue with vortex. Its likely i've messed up somewhere in this installation but for the life of me I cant figure out what.

**Comment by goober442** [comment]
Well i've made progress, the process starts but then instantly ends. I just had to install 10.9.

**Comment by goober442** [comment]
Alright, deleted the skip-pregenerate-world-space and only-pregenerate lines, the process seems to start like normal. Didn't see anything in the grass folder, but I will try again. Thanks for the help so far everyone.

**Comment by goober442** [comment]
I've successfully generated a pre cache. I had to delete those two lines to do so. It's likely it was just an issue with me so i'm sorry if I wasted your guys time. Anyway, since the issue has been resolved I will be closing this.
