### ISSUE TITLE
Not An Issue But A Question

### ISSUE THREAD

**Issue by Zanderat** [SaneEngineer/No-Grass-In-Objects-NG#7]
The readme is leaving me confused.  Are all those files actually required by a user to run?  If so, could a more robust install guide be provided?  Thank you for making this, btw!

**Comment by Zanderat** [comment]
Thank you.  So, the "## Requirements to Build" is not needed by users, only for developers?

**Comment by AllstaRawR** [comment]
Barring me misunderstanding something horribly, that is correct.

**Comment by Zanderat** [comment]
![image](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/52495909/7ab97d15-1049-4daa-ad41-266f98740920)
It works.

**Comment by Zanderat** [comment]
![New Bitmap Image](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/52495909/2166e7cb-61c3-4457-8f05-31d53e321c27)
It works.
